version: '3.8'
services:
  server:
    container_name: code-go
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code-go
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
        - "6379:6379"
    volumes:
        - redis:/data
